### ISSUE TITLE
Creating Jar Executable

### ISSUE THREAD

**Issue by aybukeertekin** [powsybl/powsybl-single-line-diagram#220]
When I create a jar executable for single line diagram viewer and run it from command prompt, I am able to see user interface. However, when I try to import a file to view I get an error: ExtensionAdderProvider not found. I am sure that the file is correct, because I was able to draw the file when I use Intellij to build and run.  

  - PowSyBl Version: 3.8.0
  - OS Version: Windows 7

**Comment by geofjamg** [comment]
Hi,
Could you give use the full stack trace?

**Comment by aybukeertekin** [comment]
Hi,

I have updated powsybl-single-line-diagram to 2.0.0. I have another problem now. I get Unsupported file error. I share stack trace with you.

".\jdk-11.0.9\bin\
java.exe" --module-path ".\javafx-sdk-11.0.2\lib" --add-modules javafx.controls,
javafx.graphics,javafx.base -jar ".\single-line-diagram-view-app\target\powsybl-
single-line-diagram-view-app-2.0.0-jar-with-dependencies.jar"
[JavaFX Application Thread] INFO com.powsybl.sld.library.ResourcesComponentLibra
ry - Loading component library from /ConvergenceLibrary...
[Thread-3] INFO com.powsybl.commons.config.PlatformConfig - Using platform confi
guration provider classic
[Thread-3] INFO com.powsybl.commons.config.PlatformConfig - Platform configurati
on defined by .properties files of directory C:\Users\BIHD\.itools
[Thread-3] INFO com.powsybl.computation.local.LocalComputationManager - LocalCom
putationConfig [localDir=C:\Users\BIHD\AppData\Local\Temp, availableCore=1]
[JavaFX Application Thread] ERROR com.powsybl.sld.view.app.AbstractSingleLineDia
gramViewer - com.powsybl.commons.PowsyblException: Unsupported file format or in
valid file.
com.powsybl.commons.PowsyblException: Unsupported file format or invalid file.
        at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:440)
        at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:454)
        at com.powsybl.sld.view.app.SingleLineDiagramViewer$1$1.call(SingleLineD
iagramViewer.java:78)
        at com.powsybl.sld.view.app.SingleLineDiagramViewer$1$1.call(SingleLineD
iagramViewer.java:73)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:14
25)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Servic
e.java:725)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Servic
e.java:724)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo
lExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo
olExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[JavaFX Application Thread] ERROR com.powsybl.sld.view.app.AbstractSingleLineDia
gramViewer - com.powsybl.commons.PowsyblException: Unsupported file format or in
valid file.
com.powsybl.commons.PowsyblException: Unsupported file format or invalid file.
        at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:440)
        at com.powsybl.iidm.import_.Importers.loadNetwork(Importers.java:454)
        at com.powsybl.sld.view.app.SingleLineDiagramViewer$1$1.call(SingleLineD
iagramViewer.java:78)
        at com.powsybl.sld.view.app.SingleLineDiagramViewer$1$1.call(SingleLineD
iagramViewer.java:73)
        at javafx.graphics/javafx.concurrent.Task$TaskCallable.call(Task.java:14
25)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$6(Servic
e.java:725)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at javafx.graphics/javafx.concurrent.Service.lambda$executeTask$7(Servic
e.java:724)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo
lExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPo
olExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by floriand-e2r** [comment]
Hi, 
What kind of file are you importing? if it is CGMES file, you're probably missing some dependencies in your jar file. Could you check if you jar contains `powsybl-cgmes-conversion` and `powsybl-triple-store-impl-rdf4j`? As described in the [tutorial](https://www.powsybl.org/pages/documentation/developer/api_guide/single-line-diagram/svg-writing.html) they are needed for importing CGMES files.
Out of curiosity, how did you build this jar file?

**Comment by floriand-e2r** [comment]
@aybukeertekin I'm closing this issue as the viewer has been moved from this repo to the new [powsybl-dev-tools repo](https://github.com/powsybl/powsybl-dev-tools/) - indeed this viewer was not included in the single-line-diagram releases, it is meant more as a dev-tool than as part of powsybl-single-line-diagram. I don't know if you still encounter that problem? Feel free to open a new issue on that new repo then!

**Comment by aybukeertekin** [comment]
Hi! I figured it out somehow. Thank you for the help.
